### ISSUE TITLE
Composer: Missing oauth dependency

### ISSUE THREAD

**Issue by kubinpetr** [iPublikuj/twitter#1]

**Comment by akadlec** [comment]
This is dev version and it is under development and not finished yet

**Comment by kubinpetr** [comment]
I now, but I am ready to be your tester :)

**Comment by akadlec** [comment]
Ok ;) now it is in testable version, so if you want you can test it

**Comment by kubinpetr** [comment]
You are like The Flash ;) 
Btw. If you start with other projects like gravatr, 500px ..... 
Can you try make Foursquare? :)
