### ISSUE TITLE
Authenticate misto authorize

### ISSUE THREAD

**Issue by jirinapravnik** [iPublikuj/twitter#2]
Nebylo by lepsi mit misto oauth/authorize oauth/authentication? Ted kdyz se nekdo prihlasi, tak i kdyz uz povoleni dal, tak musi znovu autorizovat aplikaci... Pripadne dat to jako moznost do nastaveni extension viz zde: https://dev.twitter.com/oauth/reference/get/oauth/authenticate

**Comment by akadlec** [comment]
Nikoliv: Desktop applications must use this method (and cannot use GET oauth / authenticate). a pokud uživatel povolil aplikaci tak ji znova nemusí povolovat a redirect proběhne tiše.

**Comment by jirinapravnik** [comment]
Ja tedy nevim, ted to zkousim, odhlasim se, prihlasim a musi aplikaci povolit znovu. Ostatne tam pisou i "This method differs from GET oauth / authorize in that if the user has already granted the application permission, the redirect will occur without the user having to re-approve the application." Prave authenticate tise redirectne...

Já tedy nevím, co přesně v jejich podání znamená desktop application, ale co jsem kratce googlil, tak to je podle me aplkace opravdu na desktop (klient apod) a ne pro web... Ostatne na jinem webu pouzivam authenticate

A kdyz mrknu na nejaky jejich doc, tak pisou o browser, mobile app sign in a je tam authenticate: https://dev.twitter.com/web/sign-in/implementing

**Comment by akadlec** [comment]
ok, dle docu by tam asi měla být authenticate, zřejmě jsem původně vycházel z jiné dokumentace

**Comment by jirinapravnik** [comment]
Premyslel jsem jestli poslat pull, a vidim, ze jsi hodne rychly. Diky:-)

**Comment by akadlec** [comment]
;) nz
